# Generated by Django 5.0.7 on 2024-08-01 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("Create", "Create"),
                            ("Read", "Read"),
                            ("Update", "Update"),
                            ("Delete", "Delete"),
                            ("Login", "Login"),
                            ("Logout", "Logout"),
                            ("Login Failed", "Login Failed"),
                        ],
                        max_length=15,
                    ),
                ),
                ("action_time", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Success", "Success"), ("Failed", "Failed")],
                        default="Success",
                        max_length=7,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
