# Generated by Django 5.0.7 on 2024-07-27 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=13,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(09|\\+989)\\d{9}$", "Invalid Iranian phone number."
                            )
                        ],
                        verbose_name="phone number",
                    ),
                ),
                ("code", models.PositiveSmallIntegerField(verbose_name="code")),
                ("created", models.DateTimeField(auto_now=True, verbose_name="created")),
            ],
        ),
    ]
