# Generated by Django 5.0.7 on 2024-07-29 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_otptoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otptoken",
            name="phone_number",
            field=models.CharField(
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(09|\\+989)\\d{9}$", "Invalid Iranian phone number."
                    )
                ],
                verbose_name="phone number",
            ),
        ),
    ]
