# Generated by Django 5.0.7 on 2024-08-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0003_alter_question_question_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="options",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("T", "Text"), ("C", "Check box"), ("S", "Select")],
                default="T",
                max_length=1,
            ),
        ),
    ]
