# Generated by Django 5.0.7 on 2024-08-07 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0003_alter_question_question_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="response",
            name="Process",
        ),
        migrations.AddField(
            model_name="response",
            name="process",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.process",
            ),
        ),
    ]
