# Generated by Django 5.0.7 on 2024-08-10 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0004_alter_question_options_alter_question_question_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="process",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="process",
            name="is_linear",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="surveys.form",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("T", "Text"),
                    ("N", "Number"),
                    ("CB", "Check box"),
                    ("S", "Select"),
                ],
                default="T",
                max_length=2,
            ),
        ),
    ]
