# Generated by Django 5.0.7 on 2024-08-12 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0006_alter_answer_question_alter_answer_response_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="response",
            name="Process",
        ),
        migrations.AddField(
            model_name="response",
            name="process",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="surveys.process",
            ),
        ),
    ]
