# Generated by Django 5.0.7 on 2024-08-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0007_remove_response_process_response_process"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="is_single",
            field=models.BooleanField(default=False),
        ),
    ]
